const ProtocolStage = {
    CLIENT_NAME_MESSAGE: 'CLIENT_NAME_MESSAGE',
    SERVER_POSITION_UPDATE_MESSAGE: 'SERVER_POSITION_UPDATE_MESSAGE',
    SERVER_GAME_OVER_MESSAGE: 'SERVER_GAME_OVER_MESSAGE',
    SERVER_GAME_START_MESSAGE: 'SERVER_GAME_START_MESSAGE',
    CLIENT_INPUT_MESSAGE: 'CLIENT_INPUT_MESSAGE',
    CLIENT_GAME_STOP_REQUEST: 'CLIENT_GAME_STOP_REQUEST',
};
  